ziggurat: change and make more flexible scrying pyro chain state
uqbar-dao/dev-suite pull request #33
Opened 2023-02-18 08:21 UTC by hosted-fornet

**Problem**:

1. Chain state scrying only gives state.
2. Can't manipulate that data (which is often big). 

**Solution**:

1. Scry now returns tx.s as well. 
2. Add poke similar to %pyro-agent-state with `grab` field.

**Notes**:

FYI @0x70b1a5 see new interface

WIP

2023-02-20 20:02 UTC, 0x70b1a5 requested changes

2023-02-20 20:02 UTC, 0x70b1a5 commented on lib/zig/ziggurat.hoon
>          [%add-project-link ul]
on line 2506 below be sure to change it to 
```
:^    [%test-result-num-characters ni]
    [%state-num-characters ni]
  [%compiler-error-num-lines ni]
~
```

2023-02-20 23:58 UTC, hosted-fornet commented on lib/zig/ziggurat.hoon
>          [%add-project-link ul]
Fixed in e072c2d

2023-02-21 00:00 UTC, hosted-fornet commented
@0x70b1a5 I have been debating whether to add a `town-id=@ux` to %pyro-chain-state so that it returns a `batch:ui` rather than a `(map @ux batch:ui)`. Let me know if one or the other would work better for you. Otherwise, this PR is done.

2023-02-21 04:18 UTC, hosted-fornet commented
To make this practical, I need to add imports (and probably makes sense to add to %pyro-agent-state as well -- sorry for breaking changes). Reason it is required here is that we use `merk` maps rather than stdlib maps, which means accessing elements of the maps doesn't work properly with, e.g., `get:by` since map order is not as `by` expects.

2023-02-21 06:49 UTC, hosted-fornet commented
Ok, finished adding `test-imports` field to %pyro-agent-state and %pyro-chain-state in 89c68a4.

2023-02-23 05:37 UTC, merged